apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
    - name: adminer
      port: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  selector:
    matchLabels:
        app: adminer
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest@sha256:fcf8288801f633ac1bdc75a411ead945d3b3da852b807765287c23ac34ed1033
          ports:
            - name: adminer
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
