apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
    - name: adminer
      port: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  selector:
    matchLabels:
        app: adminer
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest@sha256:51262b555d9e8ac3e1fa197eec41a3f47d05aea5520ac2ccc78a03ffc7d39b3a
          ports:
            - name: adminer
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
