apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
    - name: adminer
      port: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  selector:
    matchLabels:
        app: adminer
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest@sha256:758aa020a8d631163bc1c94a3a9b545c2e34e45c6c5f38252396f021c20c3637
          ports:
            - name: adminer
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
