apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  ports:
    - name: adminer
      port: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  selector:
    matchLabels:
        app: adminer
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest@sha256:8470b5624fc5b469755794e8dc68548f68f1b570b8329e772bc78843bdd38036
          ports:
            - name: adminer
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
