apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
spec:
  ports:
    - name: console
      port: 8080
    - name: sql
      port: 26257
  selector:
    app: cockroachdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb
spec:
  selector:
    matchLabels:
        app: cockroachdb
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach@sha256:d515b60ac6d5f0810a219f18d7d9c9b6d843c0bf919f9d042b93bb20c6e80e49
        args:
          - start-single-node
          - --insecure
        ports:
        - containerPort: 8080
          name: console
        - containerPort: 26257
          name: sql
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        volumeMounts:
        - name: data
          mountPath: /cockroach/cockroach-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cockroachdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cockroachdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
