apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
spec:
  ports:
    - name: console
      port: 8080
    - name: sql
      port: 26257
  selector:
    app: cockroachdb
---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-statefulset
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: console
      port: 8080
    - name: sql
      port: 26257
  selector:
    app: cockroachdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  selector:
    matchLabels:
      app: cockroachdb
  serviceName: cockroachdb-statefulset
  replicas: 1
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:v22.1.5
        args:
          - start-single-node
          - --insecure
        #  - --listen-addr=0.0.0.0
          - --advertise-addr=cockroachdb-0.cockroachdb-statefulset
        #  - --join=cockroachdb-0.cockroachdb-statefulset
        ports:
        - containerPort: 8080
          name: console
        - containerPort: 26257
          name: sql
        volumeMounts:
        - name: data
          mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi