apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - name: sql
      port: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
        app: mariadb
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MARIADB_USER
              value: user
            - name: MARIADB_PASSWORD
              value: secret
            - name: MARIADB_DATABASE
              value: database
            - name: MARIADB_ROOT_PASSWORD
              value: toor
          ports:
            - name: sql
              containerPort: 3306
          resources:
            limits:
              cpu: "500m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "2Gi"
          #readinessProbe:
          #  httpGet:
          #    path: /minio/health/live
          #    port: 9000
          #lifecycle:
          #  preStop:
          #    exec:
          #      command:
          #        - sh
          #        - -c
          #        - "sleep 10"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
