apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - name: sql
      port: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
        app: mariadb
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest@sha256:018e5ae1207e80a5c65e24d78d836ac4f82de5d7bf9a035c44fa06d9cb75c2f4
          env:
            - name: MARIADB_USER
              value: username
            - name: MARIADB_PASSWORD
              value: password
            - name: MARIADB_DATABASE
              value: database
            - name: MARIADB_ROOT_PASSWORD
              value: toor
          ports:
            - name: sql
              containerPort: 3306
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - echo "SELECT 1" | mariadb -u username --password=password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
