apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: s3
      port: 9000
    - name: console
      port: 9001
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
        app: minio
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: AKIAIOSFODNN7EXAMPLE
            - name: MINIO_ROOT_PASSWORD
              value: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          ports:
            - name: s3
              containerPort: 9000
            - name: console
              containerPort: 9001
          resources:
            limits:
              cpu: "500m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "2Gi"
          #readinessProbe:
          #  httpGet:
          #    path: /minio/health/live
          #    port: 9000
          #lifecycle:
          #  preStop:
          #    exec:
          #      command:
          #        - sh
          #        - -c
          #        - "sleep 10"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
