apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  ports:
    - name: http
      port: 7474
    - name: bolt
      port: 7687
  selector:
    app: neo4j
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
        app: neo4j
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j@sha256:bf61839a047685d0ab30db7d0b7174a8450b4367c8a8e67640126061e79c11ee
          env:
            - name: NEO4J_AUTH
              value: none
          ports:
            - name: http
              containerPort: 7474
            - name: bolt
              containerPort: 7687
          readinessProbe:
            httpGet:
              path: /
              port: 7474
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neo4j
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
