apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  ports:
    - name: api
      port: 9200
    - name: cluster
      port: 9600
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  selector:
    matchLabels:
        app: opensearch
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.9.0@sha256:6d1155e3913305e208a9e190afc8643bec71047242c366a6dbfe4219eafc5ea0
          env:
            - name: discovery.type
              value: single-node
          ports:
            - name: api
              containerPort: 9200
            - name: cluster
              containerPort: 9600
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: 9200
              httpHeaders:
                - name: Authorization
                  value: Basic YWRtaW46YWRtaW4=
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: opensearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
