apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
    - name: pma
      port: 80
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
        app: phpmyadmin
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest@sha256:ed87921184b59f7d8fc85c6a5f041c22758a4d4419c0ee3bac38eb7e133eaed3
          env:
            - name: PMA_USER
              value: username
            - name: PMA_PASSWORD
              value: password
            - name: PMA_HOSTS
              value: mariadb
          ports:
            - name: pma
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
