apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
    - name: pma
      port: 80
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
        app: phpmyadmin
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest@sha256:44328e7738eb732bed34fa2dd10c0e4683cbf0b87c23be2f660ea8ccfc271942
          env:
            - name: PMA_USER
              value: username
            - name: PMA_PASSWORD
              value: password
            - name: PMA_HOSTS
              value: mariadb
          ports:
            - name: pma
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
