apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: mqtt
      port: 5672
    - name: ui
      port: 15672
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
        app: rabbitmq
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4-management@sha256:7270478ec6739c137e3d7fccc250ec979b1cfdf37c3016c26273df760101bad6
          env:
            - name: RABBITMQ_MNESIA_DIR
              value: /var/lib/rabbitmq
            - name: RABBITMQ_DEFAULT_USER
              value: username
            - name: RABBITMQ_DEFAULT_PASS
              value: password
            - name: RABBITMQ_DEFAULT_VHOST
              value: vhost
          ports:
            - name: mqtt
              containerPort: 5672
            - name: ui
              containerPort: 15672
          readinessProbe:
            httpGet:
              path: /
              port: 15672
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
