apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
        app: redis
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis@sha256:d6ecc832969a4827645a083da38345327b3447772fe907e7d4311c79b4e3a06e
          args:
          - redis-server
          - --save
          - '60'
          - '1'
          - --loglevel warning
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - redis-cli ping
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
