apiVersion: v1
kind: Service
metadata:
  name: redis-insight
spec:
  ports:
    - name: ui
      port: 8001
  selector:
    app: redis-insight
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
spec:
  selector:
    matchLabels:
        app: redis-insight
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: redislabs/redisinsight
          ports:
            - name: ui
              containerPort: 8001
          readinessProbe:
            httpGet:
              path: /healthcheck/
              port: 8001
