apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  ports:
    - name: schema-registry
      port: 8081
    - name: pandaproxy
      port: 8082
    - name: kafka-api
      port: 9092
    - name: prom-and-admin
      port: 9644
  selector:
    app: redpanda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  selector:
    matchLabels:
        app: redpanda
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/vectorized/redpanda:latest@sha256:f81b4eaf2e9cb67a7024a763c6f2c2fe3890602784b629c695d264fed638fe12
          args:
            - redpanda
            - start
            - --smp
            - '1'
            - --reserve-memory
            - 0M
            - --overprovisioned
            - --node-id
            - '0'
            - --kafka-addr
            - PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr
            - PLAINTEXT://redpanda:9092
            - --pandaproxy-addr
            - PLAINTEXT://0.0.0.0:8082
            - --advertise-pandaproxy-addr
            - PLAINTEXT://redpanda:8082
          ports:
            - name: schema-registry
              containerPort: 8081
            - name: pandaproxy
              containerPort: 8082
            - name: kafka-api
              containerPort: 9092
            - name: prom-and-admin
              containerPort: 9644
          readinessProbe:
            tcpSocket:
              port: 9092
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redpanda
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
