apiVersion: v1
kind: Service
metadata:
  name: scylladb
spec:
  ports:
    - name: cql
      port: 9042
  selector:
    app: scylladb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylladb
spec:
  selector:
    matchLabels:
        app: scylladb
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: scylladb
    spec:
      containers:
        - name: scylladb
          image: scylladb/scylla@sha256:e2282c9e9444f005b2d3c0b950776e2961183b67b6cb6f0aa45ca79820784e32
          ports:
            - name: sql
              containerPort: 9042
          readinessProbe:
            tcpSocket:
              port: 9042
          volumeMounts:
            - name: data
              mountPath: /var/lib/scylla
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: scylladb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scylladb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
