name: Execute automated checks
on:
  - push
jobs:
  tilt-ci-dev:
    name: Verify tilt ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
      - name: Install tilt cli
        uses: yokawasa/action-setup-kube-tools@5fe385031665158529decddddb51d6224422836e # v0.11.1
        with:
          setup-tools: |
            tilt
          tilt: 'v0.33.20'
      - name: Verify tilt ci
        run: |
          timeout 1200 tilt ci
