name: Execute automated checks
on:
  - push
jobs:
  tilt-ci-dev:
    name: Verify tilt ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      - name: Install tilt cli
        uses: yokawasa/action-setup-kube-tools@9e25a4277af127b60011c95b6ed2da7e3b3613b1 # v0.11.2
        with:
          setup-tools: |
            tilt
          tilt: 'v0.33.21'
      - name: Verify tilt ci
        run: |
          timeout 1200 tilt ci
